### PR TITLE
Components Compliance Update

### PR DESCRIPTION
**Pull request by haruna99**
updated packages and their dependencies to the latest version

https://github.com/dotnet/dnceng/issues/3446
https://github.com/dotnet/dnceng/issues/3395
https://github.com/dotnet/dnceng/issues/3394
https://github.com/dotnet/dnceng/issues/3392
https://github.com/dotnet/dnceng/issues/3393
https://github.com/dotnet/dnceng/issues/3391
https://github.com/dotnet/dnceng/issues/3341
https://github.com/dotnet/dnceng/issues/3283
https://github.com/dotnet/dnceng/issues/3205
https://github.com/dotnet/dnceng/issues/1086

### CODE REVIEW

**Comment by haruna99** [comment]
@dotnet-policy-service agree company="Microsoft"

**Comment by missymessa** [comment]
Hmm, I don't know why this isn't running a PR build. I'd like to make sure nothing is broken in the PR build before I approve it.

**Comment by riarenas** [comment]
The PR was created when Azure devops was having a meltdown.

**Review by missymessa — APPROVED** [review]
LGTM shipit

**Pull request merged**
