### PR TITLE
Remove code coverage infrastructure in this repo

### PR DESCRIPTION
**Pull request by dougbu**
- see https://github.com/dotnet/dnceng/issues/2307
- avoid warnings about the deprecated `PublishCodeCoverageResults@v1` task
- infrastructure no longer needed (or used) according to a quick poll of the team
- remove lots of documentation about the code coverage infrastructure and previous requirements
- nit: for my sanity, address Markdown Lint warnings in the documentation
  - mostly whitespace and so on

### CODE REVIEW

**Review by missymessa — APPROVED** [review]
LGTM shipit

**Comment by dougbu** [comment]
@missymessa are you sure❔ I looked at the changes this morning and had trouble seeing what changed for what reasons. Had been working to cut things back to the coverage-related bits (but that hasn't gone well). I'll of course merge if you were able to decipher the changes&hellip;

**Comment by missymessa** [comment]
> @missymessa are you sure❔ I looked at the changes this morning and had trouble seeing what changed for what reasons. Had been working to cut things back to the coverage-related bits (but that hasn't gone well). I'll of course merge if you were able to decipher the changes…

It looks like you changed a bunch of the old readmes around the code coverage functionality and our team process. And then you pulled out the relevant steps from the YAML. I'm happy to retract my approval if you don't think I was thorough.

**Comment by dougbu** [comment]
> It looks like you changed a bunch of the old readmes around the code coverage functionality and our team process. And then you pulled out the relevant steps from the YAML. I'm happy to retract my approval if you don't think I was thorough.

That's about right except my concern wasn't your thoroughness. I was more looking at things locally w/ `git show --ignore-space-at-eol` and myself having trouble finding the signals in the noise. Have now read through the changes here (w/ whitespace turned off of course) and see that it makes them much more clear. I was about to retract my question to you 😀

**Pull request merged**
