### PR TITLE
Remove RolloutScorer Azure Function from solution

### PR DESCRIPTION
**Pull request by missymessa**
https://github.com/dotnet/dnceng/issues/4658

Retains the CLI and library functionality that does the calculations and can generate a scorecard locally, but removes the Azure Function from the code base.

### CODE REVIEW

**Comment by garath** [comment]
This doesn't remove the actual files on disk. What's the plan for those?

**Comment by missymessa** [comment]
> This doesn't remove the actual files on disk. What's the plan for those?

There's an item in the linked issue to do that. I want to remove it from deployments/code base so it doesn't get added back to Azure accidentally :)

**Review by garath — APPROVED** [review]

**Comment by garath** [comment]
> There's an item in the linked issue to do that. I want to remove it from deployments/code base so it doesn't get added back to Azure accidentally :)

Is that "Remove any code that does the markdown file generation" item? I'm nervous about having dotnet code in the repo that's no longer connected to a solution (it's super easy to overlook and forget about) but as long as the code deletion happening soon then it shouldn't be a problem.

**Comment by missymessa** [comment]
> > There's an item in the linked issue to do that. I want to remove it from deployments/code base so it doesn't get added back to Azure accidentally :)
> 
> Is that "Remove any code that does the markdown file generation" item? I'm nervous about having dotnet code in the repo that's no longer connected to a solution (it's super easy to overlook and forget about) but as long as the code deletion happening soon then it shouldn't be a problem.

No, it should be covered under: "Remove Rollout Scorer resources from Azure (e.g., the Azure function, et cetera)"

I _expect_ anything Rollout Scorer related will be deleted (from dotnet/dnceng, specifically), but I wanted to make sure I was specific in this instance, as we'll want to keep the Azure table that logs the deployment times (so that new reporting can reference that data), so I didn't want resources related to that to be deleted.

**Pull request merged**
